runtime: php83 # atau versi lain yang didukung

env_variables:
  # Masukkan semua variabel dari file .env Anda di sini
  APP_KEY: 'base64:kunci_anda_disini'
  APP_ENV: 'production'
  DB_CONNECTION: 'mysql'
  DB_SOCKET: '/cloudsql/nama-koneksi-cloud-sql-anda'
  DB_DATABASE: 'nama_database_anda'
  # ...dan seterusnya

runtime_config:
  document_root: public